SKNI_Django/Author/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('SKNI_Django.Author.views',
  url(r'^create/book/author$', 'createBookAuthor', name='createBookAuthor'),
  url(r'^update/book/author/(?P<pk>\d+)$', 'updateBookAuthor', name='updateBookAuthor'),
  url(r'^delete/book/author/(?P<pk>\d+)$', 'deleteBookAuthor', name='deleteBookAuthor'),
  url(r'^books/authors$', 'booksAuthors', name='booksAuthors'),
)

SKNI_Django/Index/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('SKNI_Django.Index.views',
  url(r'^$', 'index', name='index'),
  url(r'^index$', 'index', name='index'),
  url(r'^create/author$', 'createAuthor', name='createAuthor')  
)

SKNI_Django/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^', include('SKNI_Django.Index.urls')),
    url(r'^', include('SKNI_Django.Author.urls')),
)

SKNI_Django/Author/models.py
from SKNI_Django.Tools.models import Author

SKNI_Django/Index/models.py
from SKNI_Django.Tools.models import Author

SKNI_Django/Tools/models.py
from django.db import models

class Author(models.Model):
  first_name = models.CharField(max_length=64)
  last_name = models.CharField(max_length=64)

class Book(models.Model):
  title = models.CharField(max_length=64)
  author = models.ForeignKey(Author)
  
class Client(models.Model):
  first_name = models.CharField(max_length=64)
  last_name = models.CharField(max_length=64)
  address = models.TextField()
  
class BorrowBooks(models.Model):
  client = models.ForeignKey(Client)
  book = models.ForeignKey(Book)

SKNI_Django/Author/forms.py
from django import forms
from SKNI_Django.Author import models
class CreateAuthorModelForm(forms.ModelForm):
  class Meta:
    model = models.Author
    fields = ['first_name', 'last_name']
    labels = {
              'first_name': "First name",
              'last_name': "Last name"              
             }

SKNI_Django/Index/forms.py
from django import forms

class CreateAuthorForm(forms.Form):
  first_name = forms.CharField(max_length=64)
  last_name = forms.CharField(max_length=64)

SKNI_Django/Author/views.py
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from SKNI_Django.Author.models import Author
from SKNI_Django.Author.forms import CreateAuthorModelForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

class BooksAuthors(ListView):
  template_name = "booksAuthors.html"
  model = Author
  
booksAuthors = BooksAuthors.as_view()

class CreateBookAuthor(SuccessMessageMixin, CreateView):
  template_name = "createAuthor.html"
  form_class = CreateAuthorModelForm
  model = Author
  success_url = reverse_lazy("booksAuthors")
  success_message = u"%(first_name)s %(last_name)s is added to database."
  
createBookAuthor = CreateBookAuthor.as_view()
  
class UpdateBookAuthor(SuccessMessageMixin, UpdateView):
  template_name = "createAuthor.html"
  form_class = CreateAuthorModelForm
  model = Author
  success_url = reverse_lazy("booksAuthors")
  success_message = u"%(first_name)s %(last_name)s is changed."
  
updateBookAuthor = UpdateBookAuthor.as_view()

class DeleteBookAuthor(SuccessMessageMixin, DeleteView):
  template_name = "deleteBookAuthor.html"
  model = Author
  success_url = reverse_lazy("booksAuthors")
  success_message = u"%(first_name)s %(last_name)s is deleted."
  
deleteBookAuthor = DeleteBookAuthor.as_view()

SKNI_Django/Index/views.py
from django.views.generic import TemplateView, FormView
from SKNI_Django.Index.forms import CreateAuthorForm
from django.core.urlresolvers import reverse_lazy
from SKNI_Django.Index.models import Author

class Index(TemplateView):
    template_name="index.html"
    
index = Index.as_view()

class CreateAuthor(FormView):
  template_name = 'createAuthor.html'
  form_class = CreateAuthorForm
  success_url = reverse_lazy('index')
  
  def post(self, request, *args, **kwargs):
    response = super().post(self, request, *args, **kwargs)
    Author(first_name = request.POST["first_name"], last_name = request.POST["last_name"]).save()    
    return response
  
createAuthor = CreateAuthor.as_view()

SKNI_Django/Tools/views.py
from django.shortcuts import render

# Create your views here.

SKNI_Django/Author/templates/booksAuthors.html
{% extends "base.html" %}

{% block content %}
  <div>
    <a href="{% url 'createBookAuthor' %}">Create book author</a>
  	{% if author_list %}
  	  <ul>
  	    {% for author in author_list %}
  	      <li>
  	        {{ author.first_name }}
  	        {{ author.last_name }}
  	        <a href="{% url 'updateBookAuthor' author.pk %}">Update author</a>
  	        <a href="{% url 'deleteBookAuthor' author.pk %}">Delete author</a>
  	      </li>
  	    {% endfor %}
  	  </ul>
  	{% endif %}
  </div>
{% endblock %}

SKNI_Django/Author/templates/deleteBookAuthor.html
{% extends "base.html" %}

{% block content %}
  <form method="POST" name="form">
    {% csrf_token %}
    <button>Delete</button>
    <a href="{% url 'booksAuthors' %}">Cancel</a>
  </form>
{% endblock %}

SKNI_Django/Index/templates/base.html
<html>
  <head>
  </head>
  <body>
    {% if messages %}
	  <div>
	  	<ul>
	  	  {% for message in messages %}
	  	    <li>{{ message }}</li>
	  	  {% endfor %}
	  	</ul>
	  </div>
	{% endif %}
	
    {% block content %}
    {% endblock %}
  </body>
</html>

SKNI_Django/Index/templates/createAuthor.html
{% extends "base.html" %}

{% block content %}
  <form method="POST" name="form">
  	{% csrf_token %}
  	{{ form }}
  	<button>Save</button>
  	<a href="{% url 'index' %}">Cancel</a>
  </form>
{% endblock %}

SKNI_Django/Index/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div>Hello World from Django project for SKNI.</div>
  <div><a href="{% url 'createAuthor' %}">Create author</a></div>
  <div><a href="{% url 'booksAuthors' %}">Books author</a></div> 
{% endblock %}